### ISSUE TITLE
Get balance with param : Account_id

### ISSUE THREAD

**Issue by etiennetatur** [mateodelnorte/coinbase#11]
Hello,

Looking at the code it seems to me that the balance function will only return the default account, is there any way to pass an account_id as proposed in coinbase API (https://coinbase.com/api/doc/1.0/account/balance.html) ?

Cheers,

**Comment by mateodelnorte** [comment]
Hey @etiennetatur. Responded to the PR. Two test failing. Want to check it out and respond to the PR directly? Closing the issue so we can comment there.
