### ISSUE TITLE
doing a buy order requires unnecessary button & merchant scopes

### ISSUE THREAD

**Issue by nicktesla** [mateodelnorte/coinbase#13]
why is the /buys endpoint requesting merchant and button permissions?
like `error is:  { [Error]
  error: 'API Key does not support merchant, buttons or all scopes' }`

**Comment by nicktesla** [comment]
Actually i think i was able to fix this...buys now work..submitted a pull request here: https://github.com/mateodelnorte/coinbase/pull/14

**Comment by mateodelnorte** [comment]
fixed with #14
