### ISSUE TITLE
Will this project be continued?

### ISSUE THREAD

**Issue by levino** [mateodelnorte/coinbase#15]
With npm coinbase 1.x coinbase has pretty much rewritten it all. @mateodelnorte Do you plan on continuing this project here? I am asking because I plan to add functionality to my fork and maybe also do some pull requests. But of course if coinbase 0.x is dicontinued I could also go and alter coinbase 1.x. I personally liked your version :)

**Comment by mateodelnorte** [comment]
I'm happy to continue maintaining the 0.1.x fork. I will guide the project by asking others to help contribute pull requests which I'll curate into the branch. I won't be actively seeking feature parity with the current coinbase docs, but I'll make sure high priority issues and PRs get into master and published as quickly as possible. 

If you have improvements, make the PRs and let them rock! So far, the plan with coinbase is that we can publish updates to this repo against 0.1.We also have the option to publish the 0.1.x / previous codebase under a new module name. If that's something people want, let us know and we'll discuss the best options.

**Comment by jorilallo** [comment]
Coinbase dev here. I created a `0.1.x` branch to `coinbase/coinbase-node` where we can release fixes that reflect matt's project and thus can be released in npm if needed. It really depends how much Matt is going work on the project if this is a feasible solution or if you want to consider another release path, directly from GitHub or another NPM package. Happy to help on this.
